# Generated by Django 3.2 on 2021-05-09 06:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210509_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='attendance',
            name='discription',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='mask_details',
            field=models.BooleanField(default='False', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.employees'),
        ),
    ]
